/**
 * Argon2id (RFC 9106) — module 0.2, Key Derivation.
 *
 * The design document calls for Argon2id at 64 MiB / 3 iterations /
 * parallelism 1.  WebCrypto does not offer Argon2, so it is implemented here
 * and driven from a worker so the 64 MiB fill never blocks the interface.
 *
 * Correctness is checked against the RFC 9106 section 5 test vectors by
 * frontend/tests/crypto-vectors.test.mjs.  Do not edit this file without
 * re-running that suite.
 */

import { Blake2b } from './blake2b.js';

export const ARGON2_D = 0;
export const ARGON2_I = 1;
export const ARGON2_ID = 2;
const VERSION = 0x13;

const BLOCK_BYTES = 1024;
const WORDS_PER_BLOCK = 128;        // 64-bit words
const U32_PER_BLOCK = 256;          // low/high pairs
const ADDRESSES_PER_BLOCK = 128;
const SYNC_POINTS = 4;

// ---------------------------------------------------------------------------
// 64-bit helpers.  Each 64-bit word occupies two consecutive Uint32 slots,
// low half first.
// ---------------------------------------------------------------------------

/** v[ai] = v[ai] + v[bi] + 2 * low32(v[ai]) * low32(v[bi]) */
function fBlaMka(v, ai, bi) {
  const aLo = v[ai];
  const aHi = v[ai + 1];
  const bLo = v[bi];
  const bHi = v[bi + 1];

  // 32x32 -> 64 multiply, split into 16-bit limbs so every partial product
  // stays inside the exactly-representable float range.
  const x0 = aLo & 0xffff;
  const x1 = aLo >>> 16;
  const y0 = bLo & 0xffff;
  const y1 = bLo >>> 16;
  const p0 = x0 * y0;
  const cross = x1 * y0 + x0 * y1;
  const p3 = x1 * y1;
  const loFull = p0 + (cross % 65536) * 65536;
  let mLo = loFull >>> 0;
  let mHi = (p3 + Math.floor(cross / 65536) + Math.floor(loFull / 4294967296)) >>> 0;

  // multiply by two
  mHi = ((mHi << 1) | (mLo >>> 31)) >>> 0;
  mLo = (mLo << 1) >>> 0;

  let sumLo = (aLo >>> 0) + (bLo >>> 0);
  let carry = sumLo >= 4294967296 ? 1 : 0;
  sumLo = sumLo >>> 0;
  let sumHi = (aHi + bHi + carry) >>> 0;

  let totalLo = sumLo + mLo;
  carry = totalLo >= 4294967296 ? 1 : 0;
  v[ai] = totalLo >>> 0;
  v[ai + 1] = (sumHi + mHi + carry) >>> 0;
}

/** v[t] = rotr64(v[t] xor v[s], n) */
function xorRotr(v, t, s, n) {
  const lo = (v[t] ^ v[s]) >>> 0;
  const hi = (v[t + 1] ^ v[s + 1]) >>> 0;
  if (n === 32) {
    v[t] = hi;
    v[t + 1] = lo;
  } else if (n < 32) {
    v[t] = ((lo >>> n) | (hi << (32 - n))) >>> 0;
    v[t + 1] = ((hi >>> n) | (lo << (32 - n))) >>> 0;
  } else {
    const k = n - 32;
    v[t] = ((hi >>> k) | (lo << (32 - k))) >>> 0;
    v[t + 1] = ((lo >>> k) | (hi << (32 - k))) >>> 0;
  }
}

function G(v, a, b, c, d) {
  fBlaMka(v, a, b);
  xorRotr(v, d, a, 32);
  fBlaMka(v, c, d);
  xorRotr(v, b, c, 24);
  fBlaMka(v, a, b);
  xorRotr(v, d, a, 16);
  fBlaMka(v, c, d);
  xorRotr(v, b, c, 63);
}

function roundNoMsg(v, idx) {
  G(v, idx[0], idx[4], idx[8], idx[12]);
  G(v, idx[1], idx[5], idx[9], idx[13]);
  G(v, idx[2], idx[6], idx[10], idx[14]);
  G(v, idx[3], idx[7], idx[11], idx[15]);
  G(v, idx[0], idx[5], idx[10], idx[15]);
  G(v, idx[1], idx[6], idx[11], idx[12]);
  G(v, idx[2], idx[7], idx[8], idx[13]);
  G(v, idx[3], idx[4], idx[9], idx[14]);
}

// Precomputed Uint32 offsets for the eight row rounds and eight column rounds.
const ROW_INDEX = [];
const COL_INDEX = [];
for (let r = 0; r < 8; r += 1) {
  const row = new Uint16Array(16);
  for (let k = 0; k < 16; k += 1) row[k] = (16 * r + k) * 2;
  ROW_INDEX.push(row);

  const col = new Uint16Array(16);
  for (let k = 0; k < 16; k += 1) {
    col[k] = (2 * r + (k % 2) + 16 * Math.floor(k / 2)) * 2;
  }
  COL_INDEX.push(col);
}

// ---------------------------------------------------------------------------
// block compression
// ---------------------------------------------------------------------------
const blockR = new Uint32Array(U32_PER_BLOCK);
const blockTmp = new Uint32Array(U32_PER_BLOCK);

/**
 * next = G(prev, ref), optionally XORed into the existing `next` (Argon2 v1.3
 * XORs on every pass after the first).
 */
function fillBlock(memory, prevOffset, refOffset, nextOffset, withXor) {
  for (let i = 0; i < U32_PER_BLOCK; i += 1) {
    blockR[i] = memory[refOffset + i] ^ memory[prevOffset + i];
    blockTmp[i] = blockR[i];
  }
  if (withXor) {
    for (let i = 0; i < U32_PER_BLOCK; i += 1) blockTmp[i] ^= memory[nextOffset + i];
  }

  for (let i = 0; i < 8; i += 1) roundNoMsg(blockR, ROW_INDEX[i]);
  for (let i = 0; i < 8; i += 1) roundNoMsg(blockR, COL_INDEX[i]);

  for (let i = 0; i < U32_PER_BLOCK; i += 1) {
    memory[nextOffset + i] = blockR[i] ^ blockTmp[i];
  }
}

// ---------------------------------------------------------------------------
// H' — the variable-length hash of RFC 9106 section 3.3
// ---------------------------------------------------------------------------
function le32(value) {
  const out = new Uint8Array(4);
  out[0] = value & 0xff;
  out[1] = (value >>> 8) & 0xff;
  out[2] = (value >>> 16) & 0xff;
  out[3] = (value >>> 24) & 0xff;
  return out;
}

function hashPrime(outLength, inputs) {
  if (outLength <= 64) {
    const h = new Blake2b(outLength);
    h.update(le32(outLength));
    for (const part of inputs) h.update(part);
    return h.digest();
  }

  const out = new Uint8Array(outLength);
  const h = new Blake2b(64);
  h.update(le32(outLength));
  for (const part of inputs) h.update(part);
  let v = h.digest();
  out.set(v.subarray(0, 32), 0);

  // V1..Vr each contribute their first 32 bytes; the tail V(r+1) is emitted
  // whole.  V1 is already in hand, so r-1 more full blocks follow.
  const r = Math.ceil(outLength / 32) - 2;
  let position = 32;
  for (let i = 1; i < r; i += 1) {
    v = new Blake2b(64).update(v).digest();
    out.set(v.subarray(0, 32), position);
    position += 32;
  }
  v = new Blake2b(outLength - 32 * r).update(v).digest();
  out.set(v, position);
  return out;
}

// ---------------------------------------------------------------------------
// index selection (RFC 9106 section 3.4)
// ---------------------------------------------------------------------------
function indexAlpha(pass, lane, slice, index, laneLength, segmentLength, refLane, pseudoRand, sameLane) {
  let referenceAreaSize;
  if (pass === 0) {
    if (slice === 0) {
      referenceAreaSize = index - 1;
    } else if (sameLane) {
      referenceAreaSize = slice * segmentLength + index - 1;
    } else {
      referenceAreaSize = slice * segmentLength - (index === 0 ? 1 : 0);
    }
  } else if (sameLane) {
    referenceAreaSize = laneLength - segmentLength + index - 1;
  } else {
    referenceAreaSize = laneLength - segmentLength - (index === 0 ? 1 : 0);
  }

  // x = (J1 * J1) >> 32, then y = (referenceAreaSize * x) >> 32.
  // J1*J1 reaches 2^64, past what a double represents exactly, so the square
  // is assembled from 16-bit limbs where every partial product is exact.
  const j = pseudoRand >>> 0;
  const jLo = j & 0xffff;
  const jHi = j >>> 16;
  const x = jHi * jHi + Math.floor((2 * jHi * jLo * 65536 + jLo * jLo) / 4294967296);
  const relativePosition =
    referenceAreaSize - 1 - Math.floor((referenceAreaSize * x) / 4294967296);

  const startPosition =
    pass !== 0 ? (slice === SYNC_POINTS - 1 ? 0 : (slice + 1) * segmentLength) : 0;

  return (startPosition + relativePosition) % laneLength;
}

// ---------------------------------------------------------------------------
// main entry point
// ---------------------------------------------------------------------------

/**
 * Derive a key with Argon2.
 *
 * @param {object} options
 * @param {Uint8Array} options.password
 * @param {Uint8Array} options.salt          at least 8 bytes
 * @param {number} [options.timeCost]        iterations, default 3
 * @param {number} [options.memoryKiB]       memory in KiB, default 65536
 * @param {number} [options.parallelism]     lanes, default 1
 * @param {number} [options.hashLength]      output bytes, default 32
 * @param {number} [options.type]            ARGON2_ID by default
 * @param {Uint8Array} [options.secret]
 * @param {Uint8Array} [options.associatedData]
 * @param {(fraction: number) => void} [options.onProgress]
 * @returns {Uint8Array}
 */
export function argon2({
  password,
  salt,
  timeCost = 3,
  memoryKiB = 65536,
  parallelism = 1,
  hashLength = 32,
  type = ARGON2_ID,
  secret = new Uint8Array(0),
  associatedData = new Uint8Array(0),
  onProgress = null,
}) {
  if (!(password instanceof Uint8Array)) throw new TypeError('password must be a Uint8Array');
  if (!(salt instanceof Uint8Array) || salt.length < 8) {
    throw new Error('Argon2: salt must be at least 8 bytes');
  }
  if (timeCost < 1) throw new Error('Argon2: timeCost must be at least 1');
  if (parallelism < 1) throw new Error('Argon2: parallelism must be at least 1');
  if (memoryKiB < 8 * parallelism) {
    throw new Error('Argon2: memoryKiB must be at least 8 * parallelism');
  }
  if (hashLength < 4) throw new Error('Argon2: hashLength must be at least 4');

  // H0: 64 bytes summarising every parameter and input.
  const h0 = new Blake2b(64);
  h0.update(le32(parallelism));
  h0.update(le32(hashLength));
  h0.update(le32(memoryKiB));
  h0.update(le32(timeCost));
  h0.update(le32(VERSION));
  h0.update(le32(type));
  h0.update(le32(password.length));
  h0.update(password);
  h0.update(le32(salt.length));
  h0.update(salt);
  h0.update(le32(secret.length));
  h0.update(secret);
  h0.update(le32(associatedData.length));
  h0.update(associatedData);
  const initialHash = h0.digest();

  // Round the requested memory down to a whole number of segments.
  const memoryBlocks = Math.max(memoryKiB, 8 * parallelism);
  const segmentLength = Math.floor(memoryBlocks / (parallelism * SYNC_POINTS));
  const laneLength = segmentLength * SYNC_POINTS;
  const totalBlocks = laneLength * parallelism;

  const memory = new Uint32Array(totalBlocks * U32_PER_BLOCK);

  // First two blocks of every lane come straight from H0.
  const seed = new Uint8Array(72);
  seed.set(initialHash, 0);
  for (let lane = 0; lane < parallelism; lane += 1) {
    for (let column = 0; column < 2; column += 1) {
      seed.set(le32(column), 64);
      seed.set(le32(lane), 68);
      const block = hashPrime(BLOCK_BYTES, [seed]);
      const offset = (lane * laneLength + column) * U32_PER_BLOCK;
      const view = new DataView(block.buffer, block.byteOffset, block.byteLength);
      for (let i = 0; i < U32_PER_BLOCK; i += 1) {
        memory[offset + i] = view.getUint32(i * 4, true);
      }
    }
  }

  const zeroBlock = new Uint32Array(U32_PER_BLOCK);
  const inputBlock = new Uint32Array(U32_PER_BLOCK);
  const addressBlock = new Uint32Array(U32_PER_BLOCK);
  const scratch = new Uint32Array(U32_PER_BLOCK * 3);
  // fillBlock works on the shared `memory` array, so the address-block dance
  // borrows a scratch region laid out the same way.
  const SCRATCH_ZERO = 0;
  const SCRATCH_INPUT = U32_PER_BLOCK;
  const SCRATCH_ADDRESS = U32_PER_BLOCK * 2;

  function nextAddresses() {
    // input_block.v[6] += 1  (a 64-bit counter; the low word never wraps here)
    inputBlock[12] = (inputBlock[12] + 1) >>> 0;
    if (inputBlock[12] === 0) inputBlock[13] = (inputBlock[13] + 1) >>> 0;

    scratch.set(zeroBlock, SCRATCH_ZERO);
    scratch.set(inputBlock, SCRATCH_INPUT);
    scratch.fill(0, SCRATCH_ADDRESS, SCRATCH_ADDRESS + U32_PER_BLOCK);
    fillBlock(scratch, SCRATCH_ZERO, SCRATCH_INPUT, SCRATCH_ADDRESS, false);
    // The reference implementation applies G twice, the second time over the
    // address block itself.
    scratch.set(scratch.subarray(SCRATCH_ADDRESS, SCRATCH_ADDRESS + U32_PER_BLOCK), SCRATCH_INPUT);
    scratch.fill(0, SCRATCH_ADDRESS, SCRATCH_ADDRESS + U32_PER_BLOCK);
    fillBlock(scratch, SCRATCH_ZERO, SCRATCH_INPUT, SCRATCH_ADDRESS, false);
    addressBlock.set(scratch.subarray(SCRATCH_ADDRESS, SCRATCH_ADDRESS + U32_PER_BLOCK));
  }

  const totalSegments = timeCost * SYNC_POINTS * parallelism;
  let doneSegments = 0;

  for (let pass = 0; pass < timeCost; pass += 1) {
    for (let slice = 0; slice < SYNC_POINTS; slice += 1) {
      for (let lane = 0; lane < parallelism; lane += 1) {
        const dataIndependent =
          type === ARGON2_I || (type === ARGON2_ID && pass === 0 && slice < SYNC_POINTS / 2);

        if (dataIndependent) {
          inputBlock.fill(0);
          inputBlock[0] = pass;          // v[0], low half
          inputBlock[2] = lane;          // v[1]
          inputBlock[4] = slice;         // v[2]
          inputBlock[6] = memoryBlocks;  // v[3]
          inputBlock[8] = timeCost;      // v[4]
          inputBlock[10] = type;         // v[5]
        }

        let startIndex = 0;
        if (pass === 0 && slice === 0) {
          startIndex = 2;   // the first two blocks are already seeded
          if (dataIndependent) nextAddresses();
        }

        let currentOffset =
          (lane * laneLength + slice * segmentLength + startIndex) * U32_PER_BLOCK;
        let prevOffset =
          currentOffset % (laneLength * U32_PER_BLOCK) === 0
            ? currentOffset + (laneLength - 1) * U32_PER_BLOCK
            : currentOffset - U32_PER_BLOCK;

        for (let index = startIndex; index < segmentLength; index += 1) {
          if (currentOffset % (laneLength * U32_PER_BLOCK) === 0) {
            prevOffset = currentOffset + (laneLength - 1) * U32_PER_BLOCK;
          }

          let pseudoRandLo;
          let pseudoRandHi;
          if (dataIndependent) {
            if (index % ADDRESSES_PER_BLOCK === 0) nextAddresses();
            const at = (index % ADDRESSES_PER_BLOCK) * 2;
            pseudoRandLo = addressBlock[at];
            pseudoRandHi = addressBlock[at + 1];
          } else {
            pseudoRandLo = memory[prevOffset];
            pseudoRandHi = memory[prevOffset + 1];
          }

          const refLane =
            pass === 0 && slice === 0 ? lane : (pseudoRandHi >>> 0) % parallelism;
          const refIndex = indexAlpha(
            pass, lane, slice, index, laneLength, segmentLength,
            refLane, pseudoRandLo, refLane === lane,
          );

          const refOffset = (refLane * laneLength + refIndex) * U32_PER_BLOCK;
          fillBlock(memory, prevOffset, refOffset, currentOffset, pass !== 0);

          prevOffset = currentOffset;
          currentOffset += U32_PER_BLOCK;
        }

        doneSegments += 1;
        if (onProgress) onProgress(doneSegments / totalSegments);
      }
    }
  }

  // XOR the last block of every lane, then hash it down to the tag.
  const final = new Uint32Array(U32_PER_BLOCK);
  for (let lane = 0; lane < parallelism; lane += 1) {
    const offset = (lane * laneLength + laneLength - 1) * U32_PER_BLOCK;
    for (let i = 0; i < U32_PER_BLOCK; i += 1) final[i] ^= memory[offset + i];
  }

  const finalBytes = new Uint8Array(BLOCK_BYTES);
  const finalView = new DataView(finalBytes.buffer);
  for (let i = 0; i < U32_PER_BLOCK; i += 1) finalView.setUint32(i * 4, final[i], true);

  const tag = hashPrime(hashLength, [finalBytes]);

  // Wipe the working memory before returning; it holds key-derived state.
  memory.fill(0);
  final.fill(0);
  finalBytes.fill(0);
  return tag;
}

export function argon2id(options) {
  return argon2({ ...options, type: ARGON2_ID });
}
